### ISSUE TITLE
Bug: Karma score/AJAX voting bug

### ISSUE THREAD

**Issue by chlee0902** [stephenmcd/drum#17]
How to produce: By continuously clicking on either "Up arrow" or "Down arrow", you will notice that the karma points for the OP increase or decrease as the user clicks. 

Expected: It is only expected for the karma point to be incremented or decremented once per user.

Note: It will only affect the karma points of others. Not the current logged in user's own post.

**Comment by stephenmcd** [comment]
I can't reproduce this at all.

**Comment by chlee0902** [comment]
You can only do it on others' posts. Not your own posts.

**Comment by stephenmcd** [comment]
Yes I tried that - can you try and look into it further and determine what the cause is? That will better reveal whether there actually is a bug or not.

**Comment by chlee0902** [comment]
Forgive me for I am still a novice in using Django, Mezzanine and AJAX. But I am trying hard to figure out the problem. My guess is this line of code only caters to stop the OP from bumping up their own karma score ? 

**if rating.user != content_object.user:** 

```
@receiver(post_save, sender=Rating)
def karma(sender, **kwargs):
    """
    Each time a rating is saved, check its value and modify the
    profile karma for the related object's user accordingly.
    Since ratings are either +1/-1, if a rating is being edited,
    we can assume that the existing rating is in the other direction,
    so we multiply the karma modifier by 2.
    """
    rating = kwargs["instance"]
    value = int(rating.value)
    if not kwargs["created"]:
        value *= 2
    content_object = rating.content_object
    if rating.user != content_object.user:
        queryset = Profile.objects.filter(user=content_object.user)
        queryset.update(karma=models.F("karma") + value)
```

**Comment by stephenmcd** [comment]
I'm sorry I misread your original message as allowing the voting score to change - you're right the karma changes multiple times when it shouldn't.

Thanks
