### ISSUE TITLE
Error Python 3 when install library "topia.termextract" for auto_tag

### ISSUE THREAD

**Issue by Cajoline** [stephenmcd/drum#24]
Hi,
I installed for a project Drum and installing as the documentation mentions the library to auto_tag topia.termextract , I get the following error when I use this command 

**python manage.py auto_tag --generate=100 --assign --remove**

**ERROR:**
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.

Thank you !

**Comment by stephenmcd** [comment]
My guess is that library doesn't support Python 3. I can only guess because you didn't provide the full error. If I'm wrong, please re-open.

**Comment by Cajoline** [comment]
Yes that's what I thought, do auto_tag work without this library?
