### ISSUE TITLE
ProfileNotConfigured Error

### ISSUE THREAD

**Issue by lyricat** [stephenmcd/drum#35]
commit 880a1125f8b0701ed337cc8d1d4f6264767f0770 causes this issue. rollback to parent d863e396bbbae0348d67ae739b0e0fd5284aa9f1 and it works fine.

I try to trace the problem, and find in `mezzanine/accounts/__init__.py`, get_profile_model() doesn't get the current settings.

**Comment by stephenmcd** [comment]
The dev version of Drum is built using the dev version of Mezzanine.

**Comment by lyricat** [comment]
But If people build from source of drum, the setup flow will download the production version of Mezzanine(like what I am doing).

Can I add a "AUTH_PROFILE_MODULE" in settings to workaround? I can create a pull request.

**Comment by stephenmcd** [comment]
> But If people build from source of drum, the setup flow will download the production version of Mezzanine

That's not strictly true.

**Comment by scarygliders** [comment]
Actually, this just happened to me, after I installed drum via pip using this git repo.

So it looks like I have to use the dev version of mezzanine? Allrighty then.
