### ISSUE TITLE
Error on createdb: mezzanine.accounts.ProfileNotConfigured

### ISSUE THREAD

**Issue by COLABORATI** [stephenmcd/drum#39]
Using the master branch from this repo with ```python setup.py install``` the createdb command gives me this error: 
```
mezzanine.accounts.ProfileNotConfigured
```
What do I have to do to just get this running so I can test mezzanine? 

Thanks again for your attention.

**Comment by stephenmcd** [comment]
#35

**Comment by COLABORATI** [comment]
aha, well, thanks again for your attention. 
y not u put that in Readme, man? Why? 
Anyway, have a nice sunday, please keep up the good work!
