### ISSUE TITLE
Add build/test status

### ISSUE THREAD

**Issue by j7nn7k** [stephenmcd/drum#49]
It would be nice to have a build/test status indicator in the readme to see if all is well. Travis CI is good for that sort of stuff. What do you think?

**Comment by stephenmcd** [comment]
Sure, let's do it

**Comment by j7nn7k** [comment]
@stephenmcd I think you need to activate the drum repo under https://travis-ci.org/stephenmcd/drum for the build icon to work

**Comment by stephenmcd** [comment]
That's done
