### ISSUE TITLE
Problems starting a mezzanine project with Drum installed

### ISSUE THREAD

**Issue by kevdkav** [stephenmcd/drum#51]
Hi, I'm having some problems launching a drum project

When I use this command
`mezzanine-project -a drum project_name`

I get this error, regardless of the `project_name` used:
`CommandError: 'project_name' conflicts with the name of an existing Python module and cannot be used as a project name. Please try another name.`

Any thoughts?

Thanks

**Comment by stephenmcd** [comment]
Could you post this to the Mezzanine mailing list instead? Thanks.

**Comment by mkevac** [comment]
I have the same problem. Is there a fix?

**Comment by nikdanilov** [comment]
Hi!  The same problem.
