### ISSUE TITLE
Refresh in LinkDetail

### ISSUE THREAD

**Issue by miguelwon** [stephenmcd/drum#55]
I'm using drum to build a website and made some additions to the link_detail template, in particular added a javascript chart. The issue is that the chart is not showing when I click from the home to the respective linkdetail, only when I refresh it. Any idea why this is happening?

**Comment by stephenmcd** [comment]
It's probably conflicting with the pjax utility - you could remove that here:

https://github.com/stephenmcd/drum/blob/15c348a772b59b0e083aeadac02e05a4a2ef37c1/drum/links/templates/base.html#L30

**Comment by miguelwon** [comment]
Ok, it worked. Thanks.

2018-01-31 0:16 GMT+00:00 Stephen McDonald <notifications@github.com>:
